### ISSUE TITLE
could not get the application to run on local environment

### ISSUE THREAD

**Issue by fsouza** [segue-org/segue#2]
After following the instructions in the README file:

```
% uname -a
Darwin xikinbook.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
% python manage.py db upgrade
Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from segue.manage.commands import manager
  File "/Users/f/Projects/e/segue/segue/manage/commands/__init__.py", line 8, in <module>
    import populate
  File "/Users/f/Projects/e/segue/segue/manage/commands/populate.py", line 3, in <module>
    from tests.support.factories import *
ImportError: No module named tests.support.factories
% nosetests
Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from segue.manage.commands import manager
  File "/Users/f/Projects/e/segue/segue/manage/commands/__init__.py", line 8, in <module>
    import populate
  File "/Users/f/Projects/e/segue/segue/manage/commands/populate.py", line 3, in <module>
    from tests.support.factories import *
ImportError: No module named tests.support.factories
% nosetests
EEEEEEE
======================================================================
ERROR: Failure: ImportError (No module named tests.support.factories)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/f/Projects/e/segue/segue/manage/commands/__init__.py", line 8, in <module>
    import populate
  File "/Users/f/Projects/e/segue/segue/manage/commands/populate.py", line 3, in <module>
    from tests.support.factories import *
ImportError: No module named tests.support.factories
-------------------- >> begin captured logging << --------------------
passlib.utils.compat: DEBUG: loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x102e06c18>
passlib.utils.compat: DEBUG: loaded lazy attr 'NativeStringIO': <built-in function StringIO>
passlib.utils.compat: DEBUG: loaded lazy attr 'BytesIO': <built-in function StringIO>
passlib.registry: DEBUG: registered 'pbkdf2_sha512' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha512'>
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: ValueError (Attempted relative import beyond toplevel package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/f/Projects/e/segue/tests/account/controller_tests.py", line 9, in <module>
    from ..support.factories import *
ValueError: Attempted relative import beyond toplevel package

======================================================================
ERROR: Failure: ValueError (Attempted relative import beyond toplevel package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/f/Projects/e/segue/tests/account/service_tests.py", line 9, in <module>
    from ..support.factories import *
ValueError: Attempted relative import beyond toplevel package

======================================================================
ERROR: Failure: ValueError (Attempted relative import beyond toplevel package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/f/Projects/e/segue/tests/account/signer_tests.py", line 7, in <module>
    from ..support import SegueApiTestCase
ValueError: Attempted relative import beyond toplevel package

======================================================================
ERROR: Failure: ValueError (Attempted relative import beyond toplevel package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/f/Projects/e/segue/tests/proposal/controller_tests.py", line 11, in <module>
    from ..support import SegueApiTestCase, hashie
ValueError: Attempted relative import beyond toplevel package

======================================================================
ERROR: Failure: ValueError (Attempted relative import beyond toplevel package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/f/Projects/e/segue/tests/proposal/service_tests.py", line 9, in <module>
    from ..support import SegueApiTestCase
ValueError: Attempted relative import beyond toplevel package

======================================================================
ERROR: test_proposal_invite (mailer_service_tests.MailerServiceTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/f/Projects/e/segue/tests/mailer_service_tests.py", line 20, in setUp
    super(MailerServiceTestCases, self).setUp()
  File "/Users/f/Projects/e/segue/tests/support/__init__.py", line 13, in setUp
    self.app = segue.Application(settings_override=settings)
  File "/Users/f/Projects/e/segue/segue/__init__.py", line 18, in __init__
    self._load_configs(settings_override)
  File "/Users/f/Projects/e/segue/segue/__init__.py", line 28, in _load_configs
    self.config.from_object('segue.settings')
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/werkzeug/utils.py", line 426, in import_string
    sys.exc_info()[2])
  File "/Users/f/.venvs/segue/lib/python2.7/site-packages/werkzeug/utils.py", line 419, in import_string
    __import__(modname)
ImportStringError: import_string() failed for 'segue.settings'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'segue' found in '/Users/f/Projects/e/segue/segue/__init__.pyc'.
- 'segue.settings' not found.

Original exception:

ImportError: No module named settings

----------------------------------------------------------------------
Ran 7 tests in 0.467s

FAILED (errors=7)
```

**Comment by fmobus** [comment]
Thanks for you report. Indeed, the README file was outdated, seeing as we changed the way virtual environments are managed. Also, provisioning the box now requires ansible. An update to the README is coming soon.

**Comment by fmobus** [comment]
Added more detailed instructions with commits e45968e and d864afa.

**Comment by fsouza** [comment]
Awesome, I use parallels instead of VirtualBox locally, would you be interested in accept the changes in the Vagrantfile?

The change would look something like this: https://github.com/tsuru/tsuru-bootstrap/blob/master/Vagrantfile#L47

Thanks for your quick fix and review!
